#!/bin/bash
#
# Pre-commit hooks

# Check branch name

regex="^fix.*|^chore.*|^create-app-skeleton$|^header$|^footer$|^hero-section$|^info-section$|^subreddit-form$|^load-the-data$|^heatmap$|^posts-table$"

BRANCH_NAME_LENGTH=`git rev-parse --abbrev-ref HEAD | grep -E $regex | wc -c`

if [ ${BRANCH_NAME_LENGTH} -eq 0 ] ; then
  echo "The name of the current branch does not match any of the tasks. Please use the title of a task in Asana in lower case. Replace whitespace with a dash (-)"
  echo
  echo "Accepted branch names are:"
  echo "  create-app-skeleton"
  echo "  header"
  echo "  footer"
  echo "  hero-section"
  echo "  info-section"
  echo "  subreddit-form"
  echo "  load-the-data"
  echo "  heatmap"
  echo "  posts-table"
  echo
  echo "If you need to do something outside of the scope of a ticket like a bug fix you can alternatively prefix the branch name with fix/ or chore/"
  echo "e.g. fix/my-branch-name or chore/my-branch-name"
  echo
  exit 1
fi
