name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: yarn install

    - name: Lint
      run: yarn lint

    - name: Integration Tests
      run: yarn test

    - name: End-to-End Tests
      uses: cypress-io/github-action@v1
      with:
        start: yarn start
        # quote the url to be safe against YML parsing surprises
        wait-on: 'http://localhost:3000'

    - name: Build
      run: yarn build